#!/bin/bash

username="**USERNAME**"
password="**PASSWORD**"
address="**ADDRESS**"

hostnameIPs=$(hostname -I)

for i in $hostnameIPs;
do
    echo $i | grep -Eq "(^192\.168\.[0-9]{1,3}\.[0-9]{1,3}$|^10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$)" && localIP=$i
done

addressIP=$(host $address ns-cloud-e1.googledomains.com | grep "$address" | grep -Eo "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")

if [ "$localIP" != "$addressIP" ];
then
    curl "https://$username:$password@domains.google.com/nic/update?hostname=$address&myip=$localIP"
else
    echo "IP not changed"
fi
